version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Kafka
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  # Eureka Server
  eureka-server:
    image: openjdk:21-jdk-alpine
    container_name: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  # Spring Cloud Config Server
  config-server:
    image: openjdk:21-jdk-alpine
    container_name: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/someRepoConfig

  # API Gateway
  api-gateway:
    image: openjdk:21-jdk-alpine
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server

  # User Service
  user-service:
    image: openjdk:21-jdk-alpine
    container_name: user-service
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-server
      - config-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  # Notification Service
  notification-service:
    image: openjdk:21-jdk-alpine
    container_name: notification-service
    build:
      context: ./notification-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - eureka-server
      - config-server
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

volumes:
  postgres_data: